name: Deploy Tracker Stack

on:
  push:
    branches: [ main ]
    paths:
      - 'src/lambda/**'
      - 'infrastructure/**'
      - 'requirements.txt'
      - '.github/workflows/tracker-stack-buildspec.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
      STACK_NAME: tracker-stack
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install awscli

      - name: Create deployment directory
        run: mkdir -p deployment

      - name: Deploy CloudFormation stack
        run: |
          echo "Deploying CloudFormation stack: $STACK_NAME"
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file infrastructure/tracker-stack.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }} \
            --no-fail-on-empty-changeset


      - name: Update Lambda function code
        working-directory: ./src/lambda
        run: |
          # Process each Python file in the lambda directory
          for filepath in *;
          do
            
            filename_with_ext=${filepath##*/}
            filename_without_ext=${filename_with_ext%.*}

            echo "Processing Lambda function: $filename_without_ext"

            if [ -d "${filepath}" ]; then
              echo "This is a directory: $filepath"
              cd $filepath
              pip install -r ../../../requirements.txt -t .
              zip -r $filename_without_ext.zip *
              echo "Updating Lambda function: $filename_without_ext"
              aws lambda update-function-code \
                --function-name $filename_without_ext \
                --zip-file fileb://$filename_without_ext.zip
            else
              echo "This is a file: $filepath"
              pip install -r ../../../requirements.txt -t .
              zip -r $filename_without_ext.zip *
              ls -al
              echo "Updating Lambda function: $filename_without_ext"
              aws lambda update-function-code \
                --function-name $filename_without_ext \
                --zip-file fileb://$filename_without_ext.zip
            fi;
          done;

      - name: Clean up
        run: |
          echo "Deployment completed successfully!"